# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "archives"
  parent = ""
  name = "Lưu trữ"
  url = "/archives/"
  weight = 1
  [main.params]
    icon = "fa-solid fa-archive"

[[main]]
  identifier = "categories"
  parent = ""
  name = "Chủ đề"
  url = "/categories/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  parent = ""
  name = "Thẻ"
  url = "/tags/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "about"
  parent = ""
  name = "Giới thiệu"
  url = "/about/"
  weight = 5
  [main.params]
    icon = "fa-solid fa-user"

[[main]]
  identifier = "collections"
  parent = ""
  name = "Chuỗi bài"
  url = "/collections/"
  weight = 4
  [main.params]
    icon = "fa-solid fa-layer-group"

[[main]]
  identifier = "web-development"
  parent = "collections"
  name = "Khóa học Web Development"
  url = "/collections/web-development/"
  weight = 1
  [main.params]
    icon = "fa-solid fa-code"

[[main]]
  identifier = "travel-guides"
  parent = "collections"
  name = "Cẩm nang du lịch"
  url = "/collections/travel-guides/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-map-marked-alt"

[[main]]
  identifier = "programming-tips"
  parent = "collections"
  name = "Tips lập trình"
  url = "/collections/programming-tips/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-lightbulb"

[[main]]
  identifier = "hugo-tutorials"
  parent = "collections"
  name = "Hướng dẫn Hugo"
  url = "/collections/hugo-tutorials/"
  weight = 4
  [main.params]
    icon = "fa-solid fa-graduation-cap"
